name: Analyze Package

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Format check
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Static analysis
      - name: Analyze project source
        run: dart analyze --fatal-infos

      # Run tests
      - name: Run tests
        run: flutter test

      # PANA analysis
      - name: Dart/Flutter Package Analyzer (PANA)
        uses: flutterings/dart-package-analyzer@v1
        with:
          flutter_version: '3.19.0'
          flutter_channel: 'stable'

      # Upload PANA report as artifact (optional)
      - name: Upload PANA report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pana-report
          path: pana-output.json
