name: Analyze Package

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dart/Flutter Package Analyzer (PANA)
        uses: flutterings/dart-package-analyzer@v1
